[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tidar"
version = "0.0.1"
description = "TiDAR: Think in Diffusion, Talk in Autoregression (Unofficial)"
readme = "README.md"
requires-python = ">=3.9"
license = {text = 'AGPLv3'}
authors = [
    {name= "fish4terrisa-MSDSM", email = "fish4terrisa@fishinix.org"}
]
dependencies = [
    "torch",
    "transformers",
    "trl>=1.5.1",
    "peft",
    "accelerate",
    "bitsandbytes",
    "datasets",
    "regex"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
[project.optional-dependencies]
qlora = [
    "bitsandbytes"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["tidar*"]
